mhostetter/sdr

README.md, docs/api.rst, docs/index.rst, src/sdr/__init__.py, src/sdr/_measurement.py, tests/measurements/test_crest_factor.py, tests/measurements/test_papr.py
=> Add PAPR and crest factor measurements

src/sdr/_modulation/_pulse_shapes.py, tests/modulation/test_gaussian.py, tests/modulation/test_half_sine.py, tests/modulation/test_raised_cosine.py, tests/modulation/test_rectangular.py, tests/modulation/test_root_raised_cosine.py
- Add `sdr.rectangular()`
- Add `sdr.half_sine()`
- Add configurable normalization to each pulse shape
=> Add more pulse shapes

src/sdr/_simulation/_channel_model.py
=> Add `seed` to channel models

src/sdr/_filter/_polyphase.py
=> Better document polyphase FIR delay

src/sdr/_filter/_fir.py, src/sdr/_filter/_iir.py, src/sdr/_filter/_polyphase.py, tests/dsp/test_integrator.py
=> Add `sdr.Integrator`

docs/requirements.txt, src/sdr/_filter/_fir.py, src/sdr/_filter/_polyphase.py, src/sdr/_measurement/_modulation.py, src/sdr/_simulation/_impairment.py, src/sdr/_synchronization/_nco.py
=> Clean up block diagrams

src/sdr/_filter/_design_fir.py, tests/dsp/test_design_bandpass_fir.py
=> Add `sdr.design_bandpass_fir()`

docs/api/measurement.rst, src/sdr/_measurement/__init__.py, src/sdr/_measurement/_distance.py, tests/measurements/test_euclidean.py
=> Add `sdr.euclidean()`

src/sdr/plot/_filter.py, src/sdr/plot/_spectral_estimation.py
=> Add `y_axis` option for frequency-domain plots

src/sdr/_filter/_design_fir.py, src/sdr/plot/_filter.py
=> Add auto `x_axis` mode for filter plots

src/sdr/_filter/_design_fir.py, src/sdr/_filter/_fir.py, src/sdr/plot/_filter.py
=> Add `.group_delay()` method

src/sdr/_sequence.py, tests/sequences/test_walsh.py
=> Add Walsh codes

src/sdr/plot/_time_domain.py
=> Support explicit time input to `plot.time_domain()`

docs/examples/fir-filters.ipynb, src/sdr/plot/_filter.py, src/sdr/plot/_helper.py, src/sdr/plot/_time_domain.py
=> Make plots have minimum `ylim`

docs/api/synchronization.rst, src/sdr/_synchronization/__init__.py, src/sdr/_synchronization/_phase_error.py, tests/synchronization/test_ped.py
=> Add `sdr.PED`

src/sdr/_filter/_fir.py, tests/dsp/fir/test_differentiator.py
=> Improve differentiator bandwidth

src/sdr/_filter/_iir.py, tests/dsp/fir/test_differentiator.py, tests/dsp/iir/test_integrator.py
=> Implement backward, forward, and trapezoidal IIR integration

src/sdr/_filter/_iir.py
=> Make leaky integrator compute the average

.github/workflows/test.yaml, docs/api/synchronization.rst, pyproject.toml, src/sdr/_synchronization/__init__.py, src/sdr/_synchronization/_agc.py, src/sdr/_synchronization/_pll.py
=> Add `sdr.AGC`

src/sdr/_filter/__init__.py, src/sdr/_filter/_delay.py, src/sdr/_filter/_design_fir.py, src/sdr/_filter/_fir.py, src/sdr/plot/_filter.py
=> Add `sdr.FractionalDelay`

docs/api/dsp.rst, src/sdr/_filter/_design_multirate.py, src/sdr/_filter/_polyphase.py
=> Add `sdr.PolyphaseFIR`

.vscode/settings.json, src/sdr/_filter/_design_multirate.py, src/sdr/_filter/_polyphase.py, tests/dsp/multirate/test_design_multirate_fir.py
=> Cleanup polyphase classes

src/sdr/_filter/_design_multirate.py, src/sdr/_filter/_polyphase.py, src/sdr/_signal.py, tests/dsp/multirate/test_decimator.py, tests/dsp/multirate/test_interpolator.py, tests/dsp/multirate/test_resampler.py
=> Improve rate and delay for polyphase filters

src/sdr/plot/_spectral_estimation.py
=> Spectral plot axis tweaks

.pre-commit-config.yaml, requirements-dev.txt, src/sdr/_conversion.py
=> Fix negative condition

src/sdr/_simulation/_channel_model.py, tests/simulation/test_BinaryErasureChannel.py, tests/simulation/test_BinarySymmetricChannel.py, tests/simulation/test_DiscreteMemorylessChannel.py
=> Add discrete channel models

docs/api/coding.rst, docs/index.rst, src/sdr/__init__.py, src/sdr/_coding/__init__.py, src/sdr/_coding/_interleaver.py, src/sdr/_sequence/_conversion.py, src/sdr/_sequence/_correlation.py, src/sdr/_sequence/_maximal.py, tests/coding/test_block_interleaver.py, tests/coding/test_interleaver.py
=> Add interleavers

LICENSE, docs/conf.py, src/sdr/_coding/_scrambler.py, src/sdr/_sequence/_lfsr.py, src/sdr/_sequence/_maximal.py, tests/coding/test_additive_scrambler.py, tests/sequences/test_flfsr.py, tests/sequences/test_glfsr.py, tests/sequences/test_m_sequence.py
=> Make characteristic poly default for LFSRs

pyproject.toml, src/sdr/_sequence/_lfsr.py
=> Fix bad `type[...]` annotations

src/sdr/_link_budget/_integration.py, tests/link_budgets/test_coherent_gain.py
=> Add `coherent_gain()`

src/sdr/_detection/_coherent_integration.py
=> Support either time or frequency offset in `coherent_gain_loss()`

src/sdr/_detection/_approximation.py, src/sdr/_detection/_theory.py, src/sdr/_farrow.py, src/sdr/_modulation/_pulse_shapes.py, src/sdr/_sequence/_lfsr.py, src/sdr/_synchronization/_agc.py, src/sdr/plot/_detection.py, tests/detection/test_h0_h1_theory.py, tests/detection/test_peebles.py
=> Add `sdr.peebles()` approximation

docs/api/estimation.rst, docs/index.rst, src/sdr/__init__.py, src/sdr/_estimation/__init__.py, src/sdr/_estimation/_snr.py, tests/estimation/test_composite_snr.py
=> Add `sdr.composite_snr()`

docs/api/detection.rst, src/sdr/_detection/_coherent_integration.py, src/sdr/plot/_detection.py, src/sdr/plot/_filter.py, src/sdr/plot/_helper.py, src/sdr/plot/_modulation.py, src/sdr/plot/_spectral_estimation.py, src/sdr/plot/_time_domain.py
=> Add `ax` kwarg to all plot functions

pyproject.toml
=> Support NumPy v2

src/sdr/_simulation/_impairment.py, tests/simulation/test_clock_error.py
=> Add `sdr.clock_error()`
